/**
 * @kdl-schema/codegen-surql — KDL AST → SurrealQL DEFINE TABLE / FIELD emit。
 *
 * 用途: chronista-hub の `hub_resource` table 等、 spec から SCHEMAFULL
 * migration 文を自動生成する。 手書き SCHEMAFULL の partial-apply 罠
 * (CREO-127 でやられた case) を再発させない system level 対策。
 *
 * 対応 KDL 構造:
 *   resource-type "name" {
 *     payload {
 *       field "fname" <type> [required=#true] [description="..."]
 *     }
 *   }
 *
 * Emit 対象:
 *   - DEFINE TABLE OVERWRITE <snake_case_name> TYPE NORMAL SCHEMAFULL
 *   - DEFINE FIELD OVERWRITE <field_name> ON <table> TYPE <surrealdb-type>
 *     [ASSERT $value != NONE if required]
 *     [COMMENT '<description>']
 *     PERMISSIONS FULL
 *
 * SurrealDB type mapping:
 *   string / datetime  → string / datetime
 *   int / number       → int / number
 *   bool               → bool
 *   object             → object FLEXIBLE
 *   list               → array<unknown>
 *   enum-ref           → string fallback
 */
import type { KdlDocument, KdlNode } from '@kdl-schema/parser'
import { findNodesByName } from '@kdl-schema/parser'

export interface EmitOptions {
  /** generated header (default: true) */
  header?: boolean
  /** table 名前のケース変換 — 'kebab' (preserve) or 'snake' (default、 SQL 互換) */
  tableNameCase?: 'kebab' | 'snake'
}

const DEFAULT_HEADER = `-- ============================================================
-- AUTO-GENERATED by @kdl-schema/codegen-surql — do not edit by hand.
-- Regenerate when the source KDL spec changes.
-- ============================================================
`

function mapKdlTypeToSurql(kdlType: string): {
  type: string
  flexible?: boolean
} {
  switch (kdlType) {
    case 'string':
      return { type: 'string' }
    case 'datetime':
      return { type: 'datetime' }
    case 'int':
      return { type: 'int' }
    case 'float':
      return { type: 'float' }
    case 'number':
      return { type: 'number' }
    case 'bool':
    case 'boolean':
      return { type: 'bool' }
    case 'object':
      return { type: 'object', flexible: true }
    default:
      return { type: 'string' }
  }
}

/** kebab-case → snake_case */
function toSnakeCase(s: string): string {
  return s.replace(/-/g, '_')
}

interface FieldSpec {
  name: string
  surqlType: string
  flexible: boolean
  required: boolean
  description?: string
}

function extractFields(resourceType: KdlNode): FieldSpec[] {
  const payload = resourceType.children.find(n => n.name === 'payload')
  if (!payload) return []

  const fields: FieldSpec[] = []
  for (const child of payload.children) {
    if (child.name !== 'field') continue
    const [fieldName, fieldType] = child.values
    if (typeof fieldName !== 'string') continue

    let surqlType = 'string'
    let flexible = false
    if (
      fieldType === 'list' ||
      child.children.some(c => c.name === 'element')
    ) {
      surqlType = 'array<unknown>'
    } else if (typeof fieldType === 'string') {
      const mapped = mapKdlTypeToSurql(fieldType)
      surqlType = mapped.type
      flexible = mapped.flexible ?? false
    }

    const required = child.properties.required === true
    const description =
      typeof child.properties.description === 'string'
        ? child.properties.description
        : undefined

    fields.push({ name: fieldName, surqlType, flexible, required, description })
  }
  return fields
}

function escapeSurqlString(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function renderField(tableName: string, field: FieldSpec): string {
  const lines: string[] = [
    `DEFINE FIELD OVERWRITE ${field.name} ON ${tableName} TYPE ${field.surqlType}`,
  ]
  if (field.flexible) {
    lines.push('  FLEXIBLE')
  }
  if (field.required) {
    lines.push('  ASSERT $value != NONE')
  }
  if (field.description) {
    lines.push(`  COMMENT ${escapeSurqlString(field.description)}`)
  }
  lines.push('  PERMISSIONS FULL;')
  return lines.join('\n')
}

function renderTableBlock(
  resourceType: KdlNode,
  tableNameCase: 'kebab' | 'snake'
): string | null {
  const [typeName] = resourceType.values
  if (typeof typeName !== 'string') return null

  const tableName = tableNameCase === 'snake' ? toSnakeCase(typeName) : typeName
  const fields = extractFields(resourceType)

  const lines: string[] = [
    `-- ${typeName}`,
    `DEFINE TABLE OVERWRITE ${tableName} TYPE NORMAL SCHEMAFULL;`,
  ]
  for (const f of fields) {
    lines.push('')
    lines.push(renderField(tableName, f))
  }
  return `${lines.join('\n')}\n`
}

/**
 * KdlDocument から全 resource-type を集めて SurrealQL DEFINE 文 を emit。
 */
export function emitSurql(doc: KdlDocument, options: EmitOptions = {}): string {
  const tableNameCase = options.tableNameCase ?? 'snake'
  const parts: string[] = []
  if (options.header !== false) parts.push(DEFAULT_HEADER)

  const resourceTypes = findNodesByName(doc, 'resource-type')
  for (const rt of resourceTypes) {
    const rendered = renderTableBlock(rt, tableNameCase)
    if (rendered) parts.push(rendered)
  }

  return parts.join('\n')
}

export { toSnakeCase }
