/**
 * @kdl-schema/codegen-rust — KDL AST → Rust struct (with serde derive) emit。
 *
 * 用途: Chronista ecosystem の Rust 側 services (vp-shell 等) が World Tree
 * resource を type-safe に扱う ための struct を spec から自動生成。
 *
 * 対応 KDL 構造:
 *   resource-type "name" {
 *     payload {
 *       field "fname" <type> [required=#true] [description="..."]
 *     }
 *   }
 *
 * Rust mapping:
 *   string / datetime  → String
 *   int                → i64
 *   number / float     → f64
 *   bool / boolean     → bool
 *   object             → serde_json::Value
 *   list               → Vec<serde_json::Value>
 *   enum-ref="..."     → String fallback
 *
 * required=#true 未指定 → `Option<T>` で wrap、 `#[serde(skip_serializing_if = "Option::is_none")]`。
 */
import type { KdlDocument, KdlNode } from '@kdl-schema/parser'
import { findNodesByName } from '@kdl-schema/parser'

export interface EmitOptions {
  /** generated header (default: true) */
  header?: boolean
  /** `use serde::{Deserialize, Serialize};` を含めるか (default: true) */
  importSerde?: boolean
  /** struct に付与する derive (default: ["Debug", "Clone", "Serialize", "Deserialize"]) */
  derives?: string[]
}

const DEFAULT_HEADER = `// ============================================================
// AUTO-GENERATED by @kdl-schema/codegen-rust — do not edit by hand.
// Regenerate when the source KDL spec changes.
// ============================================================
`

const DEFAULT_DERIVES = ['Debug', 'Clone', 'Serialize', 'Deserialize']

function mapKdlTypeToRust(kdlType: string): string {
  switch (kdlType) {
    case 'string':
    case 'datetime':
      return 'String'
    case 'int':
      return 'i64'
    case 'float':
      return 'f64'
    case 'number':
      return 'f64'
    case 'bool':
    case 'boolean':
      return 'bool'
    case 'object':
      return 'serde_json::Value'
    default:
      // enum-ref="..." 等は String fallback
      return 'String'
  }
}

/** kebab/snake → PascalCase (Rust struct convention) */
function pascalCase(s: string): string {
  return s
    .split(/[-_]/)
    .filter(Boolean)
    .map(p => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}

/** Rust reserved keywords を field 名で踏まないように prefix `r#` を付ける */
const RUST_RESERVED = new Set([
  'as',
  'break',
  'const',
  'continue',
  'crate',
  'else',
  'enum',
  'extern',
  'false',
  'fn',
  'for',
  'if',
  'impl',
  'in',
  'let',
  'loop',
  'match',
  'mod',
  'move',
  'mut',
  'pub',
  'ref',
  'return',
  'self',
  'Self',
  'static',
  'struct',
  'super',
  'trait',
  'true',
  'type',
  'unsafe',
  'use',
  'where',
  'while',
  'async',
  'await',
  'dyn',
])

function escapeRustIdent(name: string): string {
  return RUST_RESERVED.has(name) ? `r#${name}` : name
}

interface FieldSpec {
  name: string
  rustType: string
  required: boolean
  description?: string
}

function extractFields(resourceType: KdlNode): FieldSpec[] {
  const payload = resourceType.children.find(n => n.name === 'payload')
  if (!payload) return []

  const fields: FieldSpec[] = []
  for (const child of payload.children) {
    if (child.name !== 'field') continue
    const [fieldName, fieldType] = child.values
    if (typeof fieldName !== 'string') continue

    let rustType = 'String'
    if (
      fieldType === 'list' ||
      child.children.some(c => c.name === 'element')
    ) {
      rustType = 'Vec<serde_json::Value>'
    } else if (typeof fieldType === 'string') {
      rustType = mapKdlTypeToRust(fieldType)
    }

    const required = child.properties.required === true
    const description =
      typeof child.properties.description === 'string'
        ? child.properties.description
        : undefined

    fields.push({ name: fieldName, rustType, required, description })
  }
  return fields
}

function renderField(field: FieldSpec): string {
  const lines: string[] = []
  if (field.description) {
    lines.push(`    /// ${field.description}`)
  }
  if (!field.required) {
    lines.push('    #[serde(skip_serializing_if = "Option::is_none")]')
  }
  const typeExpr = field.required ? field.rustType : `Option<${field.rustType}>`
  lines.push(`    pub ${escapeRustIdent(field.name)}: ${typeExpr},`)
  return lines.join('\n')
}

function renderStruct(resourceType: KdlNode, derives: string[]): string | null {
  const [typeName] = resourceType.values
  if (typeof typeName !== 'string') return null

  const structName = pascalCase(typeName)
  const fields = extractFields(resourceType)
  const deriveAttr = `#[derive(${derives.join(', ')})]`

  if (fields.length === 0) {
    return `${deriveAttr}\npub struct ${structName} {\n    // no payload fields defined\n}\n`
  }

  const body = fields.map(renderField).join('\n')
  return `${deriveAttr}\npub struct ${structName} {\n${body}\n}\n`
}

/**
 * KdlDocument から全 resource-type を集めて Rust source を emit。
 */
export function emitRust(doc: KdlDocument, options: EmitOptions = {}): string {
  const derives = options.derives ?? DEFAULT_DERIVES
  const parts: string[] = []
  if (options.header !== false) parts.push(DEFAULT_HEADER)
  if (options.importSerde !== false) {
    parts.push('use serde::{Deserialize, Serialize};\n')
  }

  const resourceTypes = findNodesByName(doc, 'resource-type')
  for (const rt of resourceTypes) {
    const rendered = renderStruct(rt, derives)
    if (rendered) parts.push(rendered)
  }

  return parts.join('\n')
}

export { escapeRustIdent, pascalCase }
