/**
 * @kdl-schema/codegen-zod — KDL AST → Zod schema emitter。
 *
 * codegen-ts の sibling — 同じ AST shape を読んで、 runtime validation 付きの
 * Zod schema を emit する。 TS type は `z.infer<typeof X>` で自動取得できるので
 * consumer は codegen-zod だけで type + validator を得られる (codegen-ts 併用不要)。
 *
 * 対応 KDL 構造:
 *   resource-type "name" {
 *     payload {
 *       field "fname" <type> [required=#true] [description="..."]
 *     }
 *   }
 *
 * Zod mapping:
 *   KDL type   → Zod
 *   string     → z.string()
 *   int        → z.number().int()
 *   number     → z.number()
 *   bool       → z.boolean()
 *   datetime   → z.string().datetime()       (ISO 8601)
 *   enum-ref   → z.string()                    (resolve は将来 tier)
 *   list { ... } → z.array(z.unknown())       (inner type は将来 tier)
 *   object     → z.record(z.string(), z.unknown())
 *
 * required=#true 未指定なら `.optional()`。
 */
import type { KdlDocument, KdlNode } from '@kdl-schema/parser'
import { findNodesByName } from '@kdl-schema/parser'

export interface EmitOptions {
  /** generated header を output に含めるか (default: true) */
  header?: boolean
  /** `import { z } from 'zod'` を含めるか (default: true) */
  importZod?: boolean
  /** `z.infer` 経由で TS type alias も一緒に emit するか (default: true) */
  emitInferred?: boolean
}

const DEFAULT_HEADER = `/**
 * AUTO-GENERATED by @kdl-schema/codegen-zod — do not edit by hand.
 * Regenerate when the source KDL spec changes.
 */
`

function mapKdlTypeToZod(kdlType: string): string {
  switch (kdlType) {
    case 'string':
      return 'z.string()'
    case 'datetime':
      return 'z.string().datetime()'
    case 'int':
      return 'z.number().int()'
    case 'float':
    case 'number':
      return 'z.number()'
    case 'bool':
    case 'boolean':
      return 'z.boolean()'
    case 'object':
      return 'z.record(z.string(), z.unknown())'
    default:
      // enum-ref=... や不明な identifier は string fallback (後続で resolve)
      return 'z.string()'
  }
}

/** kebab/snake → PascalCase */
function pascalCase(s: string): string {
  return s
    .split(/[-_]/)
    .filter(Boolean)
    .map(p => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}

interface FieldSpec {
  name: string
  zodExpr: string
  required: boolean
  description?: string
}

function extractFields(resourceType: KdlNode): FieldSpec[] {
  const payload = resourceType.children.find(n => n.name === 'payload')
  if (!payload) return []

  const fields: FieldSpec[] = []
  for (const child of payload.children) {
    if (child.name !== 'field') continue
    const [fieldName, fieldType] = child.values
    if (typeof fieldName !== 'string') continue

    let zodExpr = 'z.unknown()'
    if (
      fieldType === 'list' ||
      child.children.some(c => c.name === 'element')
    ) {
      zodExpr = 'z.array(z.unknown())'
    } else if (typeof fieldType === 'string') {
      zodExpr = mapKdlTypeToZod(fieldType)
    }

    const required = child.properties.required === true
    const description =
      typeof child.properties.description === 'string'
        ? child.properties.description
        : undefined

    fields.push({ name: fieldName, zodExpr, required, description })
  }
  return fields
}

function renderField(field: FieldSpec): string {
  let expr = field.zodExpr
  if (field.description) {
    expr = `${expr}.describe(${JSON.stringify(field.description)})`
  }
  if (!field.required) {
    expr = `${expr}.optional()`
  }
  return `  ${field.name}: ${expr}`
}

function renderSchemaBlock(
  resourceType: KdlNode,
  emitInferred: boolean
): string | null {
  const [typeName] = resourceType.values
  if (typeof typeName !== 'string') return null

  const fields = extractFields(resourceType)
  const interfaceName = pascalCase(typeName)
  const schemaName = `${interfaceName}Schema`

  const body =
    fields.length === 0
      ? '  // no payload fields defined'
      : fields.map(renderField).join(',\n')

  const schema = `export const ${schemaName} = z.object({\n${body}\n})\n`

  if (!emitInferred) return schema
  return `${schema}\nexport type ${interfaceName} = z.infer<typeof ${schemaName}>\n`
}

/**
 * KdlDocument から全 resource-type を集めて Zod schema source を emit。
 */
export function emitZod(doc: KdlDocument, options: EmitOptions = {}): string {
  const emitInferred = options.emitInferred !== false
  const parts: string[] = []
  if (options.header !== false) parts.push(DEFAULT_HEADER)
  if (options.importZod !== false) parts.push("import { z } from 'zod'\n")

  const resourceTypes = findNodesByName(doc, 'resource-type')
  for (const rt of resourceTypes) {
    const rendered = renderSchemaBlock(rt, emitInferred)
    if (rendered) parts.push(rendered)
  }

  return parts.join('\n')
}

export { pascalCase }
