/**
 * @kdl-schema/codegen-ts — KDL AST → TypeScript interface emitter。
 *
 * 対応 KDL 構造:
 *   resource-type "name" {
 *     payload {
 *       field "fname" <type> [required=#true] [description="..."]
 *     }
 *   }
 *
 * Type mapping:
 *   KDL type   → TS type
 *   string     → string
 *   int        → number
 *   number     → number
 *   bool       → boolean
 *   datetime   → string      (ISO 8601)
 *   enum-ref="..."  → string (resolve は将来 tier)
 *   list { ... }    → unknown[] (inner type は 将来 tier)
 *   object          → Record<string, unknown>
 *
 * required=#true 指定が無ければ optional (`?`) に emit。
 */
import type { KdlDocument, KdlNode } from '@kdl-schema/parser'
import { findNodesByName } from '@kdl-schema/parser'
import { pascalCase } from './naming.js'

export interface EmitOptions {
  /** generated header を output に含めるか (default: true) */
  header?: boolean
  /** keep KDL field name as-is (snake_case), or convert to camelCase (default: as-is) */
  fieldNameStyle?: 'as-is' | 'camelCase'
}

const DEFAULT_HEADER = `/**
 * AUTO-GENERATED by @kdl-schema/codegen-ts — do not edit by hand.
 * Regenerate when the source KDL spec changes.
 */
`

function mapKdlType(kdlType: string): string {
  switch (kdlType) {
    case 'string':
    case 'datetime':
      return 'string'
    case 'int':
    case 'float':
    case 'number':
      return 'number'
    case 'bool':
    case 'boolean':
      return 'boolean'
    case 'object':
      return 'Record<string, unknown>'
    default:
      // enum-ref=... や不明な identifier は string fallback
      return 'string'
  }
}

interface FieldSpec {
  name: string
  tsType: string
  required: boolean
  description?: string
}

/**
 * resource-type ノードから fields を抽出。 payload ブロック内の `field "name" <type>` を探す。
 */
function extractFields(resourceType: KdlNode): FieldSpec[] {
  const payload = resourceType.children.find(n => n.name === 'payload')
  if (!payload) return []

  const fields: FieldSpec[] = []
  for (const child of payload.children) {
    if (child.name !== 'field') continue
    const [fieldName, fieldType] = child.values
    if (typeof fieldName !== 'string') continue

    // type は values[1] か list/object 等のサブブロック
    // list は `field "items" list { element ... }` の形 → 要素型 resolve は将来 tier
    let tsType = 'unknown'
    if (
      fieldType === 'list' ||
      child.children.some(c => c.name === 'element')
    ) {
      tsType = 'unknown[]'
    } else if (typeof fieldType === 'string') {
      tsType = mapKdlType(fieldType)
    }

    const required = child.properties.required === true
    const description =
      typeof child.properties.description === 'string'
        ? child.properties.description
        : undefined

    fields.push({ name: fieldName, tsType, required, description })
  }
  return fields
}

function renderField(field: FieldSpec): string {
  const optional = field.required ? '' : '?'
  const jsdoc = field.description ? `  /** ${field.description} */\n` : ''
  return `${jsdoc}  ${field.name}${optional}: ${field.tsType}`
}

function renderResourceInterface(resourceType: KdlNode): string | null {
  const [typeName] = resourceType.values
  if (typeof typeName !== 'string') return null

  const fields = extractFields(resourceType)
  const interfaceName = pascalCase(typeName)

  if (fields.length === 0) {
    return `export interface ${interfaceName} {\n  // no payload fields defined\n}\n`
  }

  const body = fields.map(renderField).join('\n')
  return `export interface ${interfaceName} {\n${body}\n}\n`
}

/**
 * KdlDocument から全 resource-type を集めて TypeScript source を emit。
 */
export function emitTypeScript(
  doc: KdlDocument,
  options: EmitOptions = {}
): string {
  const parts: string[] = []
  if (options.header !== false) parts.push(DEFAULT_HEADER)

  const resourceTypes = findNodesByName(doc, 'resource-type')
  for (const rt of resourceTypes) {
    const rendered = renderResourceInterface(rt)
    if (rendered) parts.push(rendered)
  }

  return parts.join('\n')
}

export { camelCase, pascalCase } from './naming.js'
